services:
  shitcord:
    build: .
    links:
      - redis
    volumes:
      - ./scraper/:/app/scraper
      - ./data/:/app/data
    restart: "no"
    command: bash -c "cd /app/ && /app/venv1/bin/python3 -u -m scraper"
  redis:
    container_name: redis
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
    image: "redis:alpine"
    entrypoint: redis-server --appendonly yes